[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
scrap = "0.5.0"
image = "0.25.8"
futures-util = "0.3"